### ISSUE TITLE
Question about with-import-map-package

### ISSUE THREAD

**Issue by novascreen** [astahmer/panda-monorepo-setup#1]
Thank you so much for putting together all these examples, they've been incredibly helpful!

In the `with-import-map-package` example, isn't it problematic if i have two panda watch tasks running that write to the same folder? I've run into some issues that i think stem from this.

It seems the tradeoff with emitPackage is that [we don't get proper autocomplete](https://github.com/chakra-ui/panda/discussions/1712). I've now combined the `with-import-map-package` and `with-emit-package` approaches:

My `ui-panda` package config
```ts
import { defineConfig } from '@pandacss/dev'
import preset from './src/preset'

export default defineConfig({
	presets: [preset],

	syntax: 'object-literal',

	preflight: true,

	include: [],
	exclude: [],

	importMap: 'ui-panda-styled-system',

	outdir: '../ui-panda-styled-system',
})
```

My app config
```ts
import { defineConfig } from '@pandacss/dev'
import preset from 'ui-panda/preset'

export default defineConfig({
	presets: [preset],

	syntax: 'object-literal',

	preflight: true,

	include: [
		'./src/components/**/*.{ts,tsx,js,jsx}',
		'./src/pages/**/*.{ts,tsx,js,jsx}',
		'./node_modules/ui-panda/src/components/**/*.{ts,tsx,js,jsx}',
	],
	exclude: [],

	importMap: 'ui-panda-styled-system',

	outdir: 'ui-panda-styled-system',
	emitPackage: true,
	outExtension: 'mjs',
	forceConsistentTypeExtension: true,
})
```

I guarantee all imports use `ui-panda-styled-system` and that I it in my package.json dependencies, but in the app folder it is being overridden by panda with all the app specific stuff. I also needed to add `'./node_modules/ui-panda/src/components/**/*.{ts,tsx,js,jsx}',` to my app includes.

None of this feels great, but this is working best so far 🤔

**Comment by novascreen** [comment]
actually that still writes to the same folder because of the pnpm symlink 🤦

**Comment by novascreen** [comment]
nvm i confused myself with the different config options, i got things working according to the example. It's still strange to generate into the same folder from multiple places though 🤷

**Comment by astahmer** [comment]
you're right, I don't think writing to the same outdir is needed, I mostly did it to avoid generating 2 different folders (which I thought would be confusing), I realize it can be even more confusing this way

it's also not needed for overriding tokens as shown [here](https://github.com/astahmer/crepe-ui/blob/main/storybook/panda.config.ts#L9)

**Comment by novascreen** [comment]
It ended up working out. As usual it's tradeoffs, having multiple folders has other problems.
If you have the outdir inside your package and use aliasing, then VSCode will always suggest both imports, the package alias and the local folder and it tends to prefer the local folder 🙈 
I'll close this and reach out on Discord if I have more questions, that way more people can see the discussion.
Thanks again for all your hard work on this and all the help you're providing to the community 🙇
