### ISSUE TITLE
Question about usage with NX monorepo

### ISSUE THREAD

**Issue by gal-terra** [astahmer/panda-monorepo-setup#2]
Hi @astahmer,

First of all, thank you so much for your wonderful work here. I'm starting a new project and trying to integrate `pandacss` with an NX mono-repo structured as follows:

- `apps/web` (Next.js app)
- `libs/styles-system` - the home of `pandacss` configuration and its config file
- `libs/ui` - design system which uses the `styles-system` package and exposes [`shadow-panda`](https://github.com/kumaaa-inc/shadow-panda/tree/main) components. This folder also contains the Storybook for the UI components.

I got it working to the point where I can use the `styles-system` package in both the `web` and `ui` apps. However, I can't make it work with Storybook. Also, in the web app, it seems like the components don't honor the `shadow-panda` preset, but that might be a different story.

Here's a link to the repo: [GitHub Repo](https://github.com/gal1419/nuko). Any idea how to set it up would be very helpful.

Thanks!

**Comment by astahmer** [comment]
I don't have experience working with NX, I suggest searching through the Panda issues/discussion or discord as this has been asked and answered a few times, I'm sure you can find a working example in there

**Comment by gal-terra** [comment]
Thanks @astahmer, 

Unfortunately, I haven't found anything for my use case yet. I'll try to ask in the panda repo, thanks again!
