### ISSUE TITLE
Question about slot-recipes

### ISSUE THREAD

**Issue by frenicohansen** [astahmer/panda-monorepo-setup#3]
Hi @astahmer,
I tried to set up a monorepo with with two packages, one for the ui library and the other is the app. I set up Panda the same way as this repo https://github.com/astahmer/panda-monorepo-setup/tree/main/module-resolution/with-import-map-package.

Every styles are correctly generated excepts for the styling for some slot-recipes. Recipes on the other hand are generated correctly. Before I separated the ui library and the app, both of them were under one same package and styling for slot-recipes were correctly generated. So there should be nothing wrong with the preset.

Can you please tell me what should I check again in my current setup?

**Comment by astahmer** [comment]
can you make a minimal repro ?

**Comment by frenicohansen** [comment]
> can you make a minimal repro ?

https://github.com/frenicohansen/repro-panda-monorepo

I added some components from Park UI including the the Tooltip (use slot-recipe) and some simple components which don't use the slot-recipe. With the current setup, the page won't render properly because the tooltip component is still used there. Just remove the tooltip component and the page will render.

Weird that in this reproduction repo the page is completely blank if we use the component with slot-recipe. In my real project only the styles were not generated, but the structure is still there.

**Comment by frenicohansen** [comment]
@astahmer do you have any update on this matter?

**Comment by astahmer** [comment]
this looks related to https://github.com/chakra-ui/panda/pull/2413 which has been released in 0.36.1, is it ok after updating ?

**Comment by frenicohansen** [comment]
@astahmer thank you. That fixes the problem!
